# SPDX-FileCopyrightText: 2024 Marcellino Palerme <marcellino.palerme@inrae.fr>
#
# SPDX-License-Identifier: MIT

services:

  api:
    image: inraep2m2/service-p2m2tools-api:latest
    container_name: p2m2ToolsApi
    ports:
      - "8080:8080"
    volumes:
      - ./shareFile:/shareFile

  db:
    image: postgres:latest
    container_name: db
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - ./secrets/pg.env

volumes:
  shareFile:



  

