services:
  web:
    build: ./Dockerfile.test
    ports:
      - "80:3000"
    volumes:
      - shareFile:/shareFile
      - ./test:/EP2M2/test
    environment:
      PGPASSWORD: ep2m2
      PGUSER: ep2m2
      PGPORT: 5432
      PGDATABASE: ep2m2db

      
  api:
    image: inraep2m2/service-p2m2tools-api:latest
    container_name: p2m2ToolsApi
    volumes:
      - shareFile:/shareFile

  db:
    image: postgres:latest
    container_name: db
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      PGPASSWORD: ep2m2
      PGUSER: ep2m2
      PGPORT: 5432
      PGDATABASE: ep2m2db

volumes:
  shareFile:



  

