# © 2024 INRAE
# SPDX-FileContributor: Marcellino Palerme <marcellino.palerme@inrae.fr>
#
# SPDX-License-Identifier: MIT

services:

  api:
    image: inraep2m2/service-p2m2tools-api:latest
    container_name: p2m2ToolsApi
    ports:
      - "8080:8080"
    volumes:
      - ./shareFile:/shareFile

  db:
    image: postgres:latest
    container_name: db
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PORT: ${PGPORT}
      POSTGRES_HOST: ${PGHOST}
      POSTGRES_DB: ${PGDATABASE}

volumes:
  shareFile:



  

