# © 2024 INRAE
# SPDX-FileContributor: Marcellino Palerme <marcellino.palerme@inrae.fr>
#
# SPDX-License-Identifier: MIT

services:

  api:
    image: ghcr.io/p2m2/service-p2m2tools-api:latest
    container_name: p2m2ToolsApi
    ports:
      - "8080:8080"
    volumes:
      - ./shareFile:/shareFile

  db:
    image: quay.io/fedora/postgresql-16:latest
    container_name: db
    ports:
      - "5432:5432"
    volumes:
      - ./db:/usr/share/container-scripts/postgresql/start
    environment:
      POSTGRESQL_PASSWORD: ${PGPASSWORD}
      POSTGRESQL_USER: ${PGUSER}
      POSTGRESQL_PORT: ${PGPORT}
      POSTGRESQL_HOST: ${PGHOST}
      POSTGRESQL_DATABASE: ep2m2db
      POSTGRESQL_ADMIN_PASSWORD: ${PGPASSWORD}

volumes:
  shareFile:



  

