# © 2024 INRAE
# SPDX-FileContributor: Marcellino Palerme <marcellino.palerme@inrae.fr>
#
# SPDX-License-Identifier: MIT

services:

  web:
    build: .
    ports:
      - "80:3000"
    volumes:
      - shareFile:/shareFile
    env_file:
      - ./secrets/global.env
      - ./environment/pg_web.env
    restart: "always"

      
  api:
    image: ghcr.io/p2m2/service-p2m2tools-api:latest
    container_name: p2m2ToolsApi
    volumes:
      - shareFile:/shareFile

  db:
    image: quay.io/fedora/postgresql-16:latest
    container_name: db
    volumes:
      - ./db:/usr/share/container-scripts/postgresql/start
    env_file:
      - ./secrets/global.env
      - ./environment/pg.env
    restart: "always"



volumes:
  shareFile:



  

