# © 2024 INRAE
# SPDX-FileContributor: Marcellino Palerme <marcellino.palerme@inrae.fr>
#
# SPDX-License-Identifier: MIT

services:      
  api:
    image: ghcr.io/p2m2/service-p2m2tools-api:latest
    container_name: p2m2ToolsApi
    volumes:
      - shareFile:/shareFile

  db:
    image: quay.io/fedora/postgresql-16:latest
    container_name: db
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - ./secrets/global.env
      - ./environment/pg.env

volumes:
  shareFile:



  

