# © 2024 INRAE
# SPDX-FileContributor: Marcellino Palerme <marcellino.palerme@inrae.fr>
#
# SPDX-License-Identifier: MIT

# thx:
# https://stackoverflow.com/a/65389878
# https://stackoverflow.com/a/67840292
name: REUSE Compliance Check

on:
  push:
    branches: '*'

permissions: 
  contents: write
  pull-requests: write
  checks: write

jobs:
  Check-REUSE-compliant:
    runs-on: ubuntu-latest
    steps:
    # Load my repo
    - uses: actions/checkout@v4
    # Check if futur new repo is REUSE compliant
    - name: REUSE Compliance Check
      uses: fsfe/reuse-action@v3
      with:
        args: --include-submodules lint
    - name: Badge not REUSE compliant
      if: ${{ failure() }}
      uses: jaywcjlove/generated-badges@main
      with:
        label: Reuse compliant
        status: NO
        color: 'red'
        output: badges/reuse_compliant.svg
    - name: Badge REUSE compliant
      if: ${{ success() }}
      uses: jaywcjlove/generated-badges@main
      with:
        label: Reuse compliant
        status: YES
        color: 'green'
        output: badges/reuse_compliant.svg
    - name: Commit badge
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git pull --rebase
        git add badges/reuse_compliant.svg
        git commit -m "Add REUSE compliant badge"
        git push
    - uses: jaywcjlove/github-action-modify-file-content@main
      with:
        path: README.md
        openDelimiter: <!--REUSE-->
        closeDelimiter: <!--REUSE_END-->
        body: |
          </br>
          [![Reuse compliant](./badges/reuse_compliant.svg)]](https://github.com/p2m2/EP2M2/actions/runs/${{ github.run_id }})
        