name: Tests Unit

on:
  push:
    branches: '*'

permissions: 
  contents: read
  pull-requests: write
  checks: write

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      service-p2m2tool-api:
        image: inraep2m2/service-p2m2tools-api
        ports:
          - 8080:8080
      db:
        image: postgres:latest
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: ep2m2
          POSTGRES_DB: ep2m2db
          POSTGRES_USER: ep2m2
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    
    steps:
      - name: Get repo
        uses: actions/checkout@v3
      - name: Test in container with compose
        run: docker compose -f "compose.test.yaml" up -d --build 
      - name: Test & coverage
        run: npm run coverage
      - name: Report coverage
        if: always()
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          file-coverage-mode: all
      - name: Summary Tests
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            test/**/*.xml
      - name: Complet report tests
        uses: dorny/test-reporter@v1
        if: always()
        with:
          reporter: "java-junit"
          name: Test Unit
          path: test/**/*.xml