name: Tests Unit

on:
  push:
    branches: '*'

permissions: 
  contents: read
  pull-requests: write
  checks: write

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Get repo
        uses: actions/checkout@v3
      - name: Test in container with compose
        run: docker compose -f "compose.test.yaml" up -d --build 
      - name: Wait end execute tests
        run: timeout 60s sh -c 'until !(docker ps | grep ep2m2_web); do sleep 2; done'
      - name: Report coverage
        if: always()
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          file-coverage-mode: all
          working-directory: ./test
      - name: Summary Tests
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            test/**/*.xml
      - name: Complet report tests
        uses: dorny/test-reporter@v1
        if: always()
        with:
          reporter: "java-junit"
          name: Test Unit
          path: test/**/*.xml